services:
  justin_bookmarks:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: unless-stopped
    container_name: justin_bookmarks

  # Optional: Add nginx reverse proxy for SSL/domain routing
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - bookmarks-app
  #   restart: unless-stopped
